const W=16,H=12;
const MAPS=[
['Crossroads',['################','#..............#','#.####.#####.#.#','#.#..#.#...#.#.#','#.#..#.#.#.#...#','#....#...#.....#','#.######.#.###.#','#........#.....#','#.######.#####.#','#..............#','#..............#','################']],
['Rooms',['################','#......#.......#','#.####.#.#####.#','#.#....#.....#.#','#.#.########.#.#','#.#............#','#.####.#####.###','#......#.......#','#.####.#.#####.#','#......#.......#','#..............#','################']],
['Dead Ends',['################','#..............#','#.#####.#####..#','#.#...#.#...#..#','#.#.#.#.#.#.####','#...#...#.#....#','###.#####.####.#','#...#.......#..#','#.#.#######.#..#','#.#...........##','#..............#','################']],
['Labyrinth',['################','#.....#........#','#.###.#.######.#','#.#...#....#...#','#.#.####.#.#.###','#.#......#.#...#','#.######.#.###.#','#......#.#.....#','#.####.#.#####.#','#....#..........#','#...............#','################']],
['Fortress',['################','#....#.........#','#.##.#.#######.#','#.#..#.#.......#','#.#.##.#.#####.#','#...#..#.....#.#','###.#.####.#.#.#','#...#......#...#','#.########.###.#','#..............#','#..............#','################']]
];
const $=id=>document.getElementById(id),menu=$('menu'),canvas=$('game'),ctx=canvas.getContext('2d');
const hostPanel=$('hostPanel'),joinPanel=$('joinPanel'),status=$('status');
let peer=null,isHost=false,myId='',map=[],mapName='',players={},conn=null,hostConns=[];
let running=false,last=0,lastNet=0,lastStab=0,keys={},flash='',controlMode='keyboard';
let touchX=0,touchY=0,touchStab=false,stickActive=false,lookActive=false,lastLookX=0;
let me={x:1.5,y:1.5,a:0,alive:true};
const MAX=8;
function statusText(s){status.textContent=s;}
function chooseMap(){const m=MAPS[Math.floor(Math.random()*MAPS.length)];mapName=m[0];map=m[1].map(r=>r.split('').map(c=>c==='#'?1:0));}
function blocked(x,y){const xx=Math.floor(x),yy=Math.floor(y);return xx<0||yy<0||xx>=W||yy>=H||map[yy][xx]===1;}
function spawn(){const a=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(!map[y][x]){const p=[x+.5,y+.5];if(!Object.values(players).some(q=>q.alive&&Math.hypot(q.x-p[0],q.y-p[1])<1.25))a.push(p);}const p=a.length?a[Math.floor(Math.random()*a.length)]:[1.5,1.5];return [p[0],p[1],Math.random()*Math.PI*2];}
function send(c,m){if(c&&c.open)c.send(m);}
function broadcast(m){hostConns.forEach(c=>send(c,m));}
function makePeer(id){return new Promise((resolve,reject)=>{const p=id?new Peer(id):new Peer();peer=p;let done=false;const timer=setTimeout(()=>{if(!done){done=true;reject(new Error('Timed out'));}},12000);p.on('open',()=>{if(done)return;done=true;clearTimeout(timer);resolve();});p.on('error',e=>{if(!done){done=true;clearTimeout(timer);reject(e);}});});}
function wire(c){c.on('data',m=>message(c,m));c.on('close',()=>{hostConns=hostConns.filter(x=>x!==c);if(isHost&&c.pid){delete players[c.pid];broadcast({t:'snap',p:players});statusText('Player left.');}else if(!isHost){conn=null;statusText('Disconnected from host.');}});c.on('error',()=>statusText('Connection error.'));}
async function hostGame(){const b=$('hostBtn');if(b.disabled)return;if(typeof Peer==='undefined'){statusText('Network library failed to load.');return;}b.disabled=true;isHost=true;myId='host';chooseMap();const s=spawn();me={x:s[0],y:s[1],a:s[2],alive:true};players={host:{id:'host',x:me.x,y:me.y,a:me.a,alive:true,k:0}};const code='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'.split('').sort(()=>Math.random()-.5).slice(0,4).join('');$('partyCode').textContent=code;$('hostWait').textContent='Share this code with the other players.';statusText('Creating party...');try{await makePeer(code);peer.on('connection',c=>{if(hostConns.length>=MAX-1){c.close();return;}hostConns.push(c);c.on('open',()=>statusText('Player connected.'));wire(c);});$('mapName').textContent=mapName;start();statusText('Party '+code+' is ready.');}catch(e){isHost=false;b.disabled=false;statusText('Could not create party: '+e.message);}}
async function joinGame(){const b=$('joinBtn');if(b.disabled)return;if(typeof Peer==='undefined'){statusText('Network library failed to load.');return;}const code=$('partyInput').value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code)){statusText('Enter exactly 4 letters/numbers.');return;}b.disabled=true;isHost=false;myId=Math.random().toString(36).slice(2,10);statusText('Connecting...');try{await makePeer();conn=peer.connect(code,{reliable:true});wire(conn);conn.on('open',()=>{statusText('Connected. Loading arena...');send(conn,{t:'hello',id:myId});});setTimeout(()=>{if(!running&&conn&&!conn.open){b.disabled=false;statusText('Could not connect to that party.');}},12000);}catch(e){b.disabled=false;statusText('Could not connect: '+e.message);}}
function message(c,m){if(!m)return;if(isHost){if(m.t==='hello'){if(players[m.id])return;if(Object.keys(players).length>=MAX){send(c,{t:'full'});c.close();return;}c.pid=m.id;const s=spawn();players[m.id]={id:m.id,x:s[0],y:s[1],a:s[2],alive:true,k:0};send(c,{t:'state',map:map,players:players,id:m.id,mapName:mapName});broadcast({t:'snap',p:players});}else if(m.t==='input'&&players[m.id]){const p=players[m.id];p.x=m.x;p.y=m.y;p.a=m.a;if(m.attack&&performance.now()-lastStab>350){lastStab=performance.now();stab(m.id);}}return;}if(m.t==='state'){map=m.map;players=m.players;myId=m.id;mapName=m.mapName||'Arena';$('mapName').textContent=mapName;if(players[myId])Object.assign(me,{x:players[myId].x,y:players[myId].y,a:players[myId].a,alive:players[myId].alive});start();}else if(m.t==='snap'){players=m.p||{};if(players[myId])Object.assign(me,{x:players[myId].x,y:players[myId].y,a:players[myId].a,alive:players[myId].alive});}else if(m.t==='hit'){flash=m.victim===myId?'STABBED!':'HIT!';setTimeout(()=>flash='',700);}else if(m.t==='full'){statusText('That party is full.');}}
function stab(id){const a=players[id];if(!a||!a.alive)return;for(const k in players){const b=players[k];if(k===id||!b.alive)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>.95)continue;const diff=Math.atan2(Math.sin(Math.atan2(dy,dx)-a.a),Math.cos(Math.atan2(dy,dx)-a.a));if(Math.abs(diff)>.72)continue;const back=Math.atan2(a.y-b.y,a.x-b.x);if(Math.cos(back-b.a)<=0){const s=spawnFor(k);b.x=s[0];b.y=s[1];b.a=s[2];b.alive=true;a.k++;broadcast({t:'hit',victim:k,respawn:{id:k,x:b.x,y:b.y,a:b.a}});}}}
function spawnFor(id){const candidates=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(!map[y][x]){const p=[x+.5,y+.5];if(Object.entries(players).every(([k,q])=>k===id||!q.alive||Math.hypot(q.x-p[0],q.y-p[1])>=1.25))candidates.push(p);}const p=candidates.length?candidates[Math.floor(Math.random()*candidates.length)]:[1.5,1.5];return [p[0],p[1],Math.random()*Math.PI*2];}
function start(){if(running)return;if(!isHost&&(!conn||!conn.open))return;running=true;menu.hidden=true;canvas.hidden=false;$('hud').hidden=false;$('touchControls').hidden=controlMode!=='touch';document.body.classList.toggle('touchMode',controlMode==='touch');$('controlHint').textContent=controlMode==='touch'?'Drag left to move · drag right to look · STAB':'WASD · mouse · SPACE';resize();requestAnimationFrame(loop);}
function resize(){canvas.width=Math.min(innerWidth,1280);canvas.height=Math.min(innerHeight,720);}
function move(dx,dy){if(!blocked(me.x+dx,me.y)&&!blocked(me.x+dx,me.y+.15)&&!blocked(me.x+dx,me.y-.15))me.x+=dx;if(!blocked(me.x,me.y+dy)&&!blocked(me.x+.15,me.y+dy)&&!blocked(me.x-.15,me.y+dy))me.y+=dy;}
function ray(a){let x=me.x,y=me.y,d=0,sx=Math.cos(a),sy=Math.sin(a);while(d<30){x+=sx*.025;y+=sy*.025;d+=.025;if(blocked(x,y))break;}return d;}
function drawCube(p,d,a,w,h){const x=w/2+Math.tan(a)/Math.tan(Math.PI/6)*w/2;const size=Math.min(h*1.35,h/(d*.72));const s=Math.max(12,size*.42),top=h/2-size*.62,bottom=top+s;const depth=s*.24;const facing=Math.cos(p.a-(me.a+a+Math.PI))>0;const sideRight=Math.cos(p.a-(me.a+a+Math.PI/2))>0;ctx.lineWidth=1;ctx.strokeStyle='#071108';
ctx.fillStyle=facing?'#238bd1':'#1d913b';ctx.beginPath();ctx.moveTo(x-s/2,top+depth);ctx.lineTo(x+s/2,top+depth);ctx.lineTo(x+s/2,bottom+depth);ctx.lineTo(x-s/2,bottom+depth);ctx.closePath();ctx.fill();ctx.stroke();
ctx.fillStyle='#32bd50';ctx.beginPath();if(sideRight){ctx.moveTo(x+s/2,top+depth);ctx.lineTo(x+s/2+depth,top);ctx.lineTo(x+s/2+depth,bottom);ctx.lineTo(x+s/2,bottom+depth);}else{ctx.moveTo(x-s/2-depth,top);ctx.lineTo(x-s/2,top+depth);ctx.lineTo(x-s/2,bottom+depth);ctx.lineTo(x-s/2-depth,bottom);}ctx.closePath();ctx.fill();ctx.stroke();
ctx.fillStyle='#2a9b43';ctx.beginPath();ctx.moveTo(x-s/2-depth,top);ctx.lineTo(x+s/2-depth,top);ctx.lineTo(x+s/2+depth,top+depth);ctx.lineTo(x-s/2+depth,top+depth);ctx.closePath();ctx.fill();ctx.stroke();}
function render(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#171923';ctx.fillRect(0,0,w,h/2);ctx.fillStyle='#29251f';ctx.fillRect(0,h/2,w,h/2);const f=Math.PI/3,n=Math.ceil(w/3);for(let i=0;i<n;i++){const a=me.a-f/2+f*(i+.5)/n,d=ray(a)*Math.cos(a-me.a),hh=Math.min(h*2,h/Math.max(.01,d)),s=Math.max(25,150-d*4.2);ctx.fillStyle=`rgb(${s},${s},${Math.min(255,s+8)})`;ctx.fillRect(i*w/n,h/2-hh/2,w/n+1,hh);}const visible=[];for(const k in players){const p=players[k];if(k===myId||!p.alive)continue;const dx=p.x-me.x,dy=p.y-me.y,d=Math.hypot(dx,dy),angle=Math.atan2(dy,dx),a=Math.atan2(Math.sin(angle-me.a),Math.cos(angle-me.a));if(Math.abs(a)<f*.78&&ray(angle)>d-.25)visible.push({p,d,a});}visible.sort((a,b)=>b.d-a.d);for(const q of visible)drawCube(q.p,q.d,q.a,w,h);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(w/2-8,h/2);ctx.lineTo(w/2+8,h/2);ctx.moveTo(w/2,h/2-8);ctx.lineTo(w/2,h/2+8);ctx.stroke();if(flash){ctx.fillStyle='#fff';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText(flash,w/2,h*.25);}}
function loop(t){const dt=Math.min(.04,(t-last||16)/1000);last=t;if(me.alive){const v=2.7*dt;let fx=0,fy=0;if(controlMode==='touch'){fx=touchX;fy=touchY;}else{if(keys.KeyW)fy-=1;if(keys.KeyS)fy+=1;if(keys.KeyA)fx-=1;if(keys.KeyD)fx+=1;}if(fx||fy){const len=Math.hypot(fx,fy)||1;fx/=len;fy/=len;move((Math.cos(me.a)*-fy+Math.cos(me.a+Math.PI/2)*fx)*v,(Math.sin(me.a)*-fy+Math.sin(me.a+Math.PI/2)*fx)*v);}}if(isHost){const p=players.host;if(p){p.x=me.x;p.y=me.y;p.a=me.a;}if((keys.Space||touchStab)&&t-lastStab>350){lastStab=t;stab('host');}}if(t-lastNet>50){lastNet=t;if(isHost)broadcast({t:'snap',p:players});else send(conn,{t:'input',id:myId,x:me.x,y:me.y,a:me.a,attack:!!(keys.Space||touchStab)});}touchStab=false;render();$('players').textContent='Players: '+Object.keys(players).length;$('state').textContent=me.alive?'Alive — flank them':'ELIMINATED';requestAnimationFrame(loop);}
function setupTouch(){const stick=$('stick'),knob=$('knob'),look=$('lookArea'),stabButton=$('stabTouch');if(!stick)return;function stickMove(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=43,len=Math.hypot(dx,dy),scale=Math.min(1,max/(len||1));const x=dx*scale,y=dy*scale;knob.style.transform=`translate(${x}px,${y}px)`;touchX=x/max;touchY=y/max;}stick.addEventListener('pointerdown',e=>{stickActive=true;stick.setPointerCapture(e.pointerId);stickMove(e)});stick.addEventListener('pointermove',e=>{if(stickActive)stickMove(e)});stick.addEventListener('pointerup',()=>{stickActive=false;touchX=touchY=0;knob.style.transform='translate(0,0)'});stick.addEventListener('pointercancel',()=>{stickActive=false;touchX=touchY=0;knob.style.transform='translate(0,0)'});look.addEventListener('pointerdown',e=>{lookActive=true;look.setPointerCapture(e.pointerId);lastLookX=e.clientX});look.addEventListener('pointermove',e=>{if(lookActive){me.a+=(e.clientX-lastLookX)*.006;lastLookX=e.clientX}});look.addEventListener('pointerup',()=>lookActive=false);look.addEventListener('pointercancel',()=>lookActive=false);stabButton.addEventListener('pointerdown',e=>{e.preventDefault();touchStab=true});}
$('keyboardChoice').onclick=()=>{controlMode='keyboard';$('controlPrompt').hidden=true;menu.hidden=false;};
$('touchChoice').onclick=()=>{controlMode='touch';$('controlPrompt').hidden=true;menu.hidden=false;};
$('hostTab').onclick=()=>{hostPanel.hidden=false;joinPanel.hidden=true;statusText('Ready to host a game.');};
$('joinTab').onclick=()=>{hostPanel.hidden=true;joinPanel.hidden=false;statusText("Enter the host's party code.");$('partyInput').focus();};
$('hostBtn').onclick=hostGame;$('joinBtn').onclick=joinGame;$('partyInput').oninput=e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4)};
window.onkeydown=e=>{keys[e.code]=true;if(e.code==='Space')e.preventDefault()};window.onkeyup=e=>{keys[e.code]=false};canvas.onclick=()=>{if(controlMode==='keyboard'&&canvas.requestPointerLock)canvas.requestPointerLock()};document.onmousemove=e=>{if(controlMode==='keyboard'&&document.pointerLockElement===canvas)me.a+=e.movementX*.0025};window.onresize=resize;setupTouch();
