const W=16,H=12;
const MAPS=[
['Crossroads',['################','#..............#','#.####.#####.#.#','#.#..#.#...#.#.#','#.#..#.#.#.#...#','#....#...#.....#','#.######.#.###.#','#........#.....#','#.######.#####.#','#..............#','#..............#','################']],
['Rooms',['################','#......#.......#','#.####.#.#####.#','#.#....#.....#.#','#.#.########.#.#','#.#............#','#.####.#####.###','#......#.......#','#.####.#.#####.#','#......#.......#','#..............#','################']],
['Dead Ends',['################','#..............#','#.#####.#####..#','#.#...#.#...#..#','#.#.#.#.#.#.####','#...#...#.#....#','###.#####.####.#','#...#.......#..#','#.#.#######.#..#','#.#...........##','#..............#','################']],
['Labyrinth',['################','#.....#........#','#.###.#.######.#','#.#...#....#...#','#.#.####.#.#.###','#.#......#.#...#','#.######.#.###.#','#......#.#.....#','#.####.#.#####.#','#....#..........#','#...............#','################']],
['Fortress',['################','#....#.........#','#.##.#.#######.#','#.#..#.#.......#','#.#.##.#.#####.#','#...#..#.....#.#','###.#.####.#.#.#','#...#......#...#','#.########.###.#','#..............#','#..............#','################']]
];
const $=id=>document.getElementById(id),menu=$('menu'),canvas=$('game'),ctx=canvas.getContext('2d'),status=$('status');
let peer=null,isHost=false,myId='',map=[],mapName='',players={},conn=null,hostConns=[];
let running=false,last=0,lastNet=0,lastStab=0,keys={},flash='';
let controlMode=window.gameControlMode||document.body.getAttribute('data-controls')||'keyboard';
let touchX=0,touchY=0,touchStab=false,stickActive=false,lookActive=false,lastLookX=0;
let me={x:1.5,y:1.5,a:0,alive:true};
const MAX=8,FOV=Math.PI/3,CAM_H=.62,KNIFE_RANGE=1.0;
function statusText(s){if(status)status.textContent=s}
function chooseMap(){const m=MAPS[Math.floor(Math.random()*MAPS.length)];mapName=m[0];map=m[1].map(r=>r.split('').map(c=>c==='#'?1:0))}
function blocked(x,y){const xx=Math.floor(x),yy=Math.floor(y);return xx<0||yy<0||xx>=W||yy>=H||map[yy][xx]===1}
function spawnFor(id){const spots=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(!map[y][x]){const p=[x+.5,y+.5];if(Object.entries(players).every(([k,q])=>k===id||!q.alive||Math.hypot(q.x-p[0],q.y-p[1])>=1.25))spots.push(p)}const p=spots.length?spots[Math.floor(Math.random()*spots.length)]:[1.5,1.5];return[p[0],p[1],Math.random()*Math.PI*2]}
function send(c,m){if(c&&c.open)c.send(m)}
function broadcast(m){hostConns.forEach(c=>send(c,m))}
function makePeer(id){return new Promise((resolve,reject)=>{const p=id?new Peer(id):new Peer();peer=p;let done=false;const timer=setTimeout(()=>{if(!done){done=true;reject(new Error('Timed out'))}},12000);p.on('open',()=>{if(done)return;done=true;clearTimeout(timer);resolve()});p.on('error',e=>{if(!done){done=true;clearTimeout(timer);reject(e)}})})}
function wire(c){c.on('data',m=>message(c,m));c.on('close',()=>{if(isHost){hostConns=hostConns.filter(x=>x!==c);if(c.pid){delete players[c.pid];broadcast({t:'snap',p:players})}}else{conn=null;statusText('Disconnected from host.')}});c.on('error',()=>statusText('Connection error.'))}
async function hostGame(){const b=$('hostBtn');if(b.disabled)return;if(typeof Peer==='undefined'){statusText('Network library failed to load.');return}b.disabled=true;isHost=true;myId='host';chooseMap();const s=spawnFor('host');me={x:s[0],y:s[1],a:s[2],alive:true};players={host:{id:'host',x:me.x,y:me.y,a:me.a,alive:true,k:0}};const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code='';for(let i=0;i<4;i++)code+=chars[Math.floor(Math.random()*chars.length)];$('partyCode').textContent=code;$('hostWait').textContent='Share this code with the other players.';statusText('Creating party...');try{await makePeer(code);peer.on('connection',c=>{if(hostConns.length>=MAX-1){c.close();return}hostConns.push(c);wire(c)});$('mapName').textContent=mapName;start();statusText('Party '+code+' is ready.')}catch(e){isHost=false;b.disabled=false;statusText('Could not create party: '+e.message)}}
async function joinGame(){const b=$('joinBtn');if(b.disabled)return;if(typeof Peer==='undefined'){statusText('Network library failed to load.');return}const code=$('partyInput').value.trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code)){statusText('Enter exactly 4 letters/numbers.');return}b.disabled=true;isHost=false;myId=Math.random().toString(36).slice(2,10);statusText('Connecting...');try{await makePeer();conn=peer.connect(code,{reliable:true});wire(conn);conn.on('open',()=>{statusText('Connected. Loading arena...');send(conn,{t:'hello',id:myId})});setTimeout(()=>{if(!running&&conn&&!conn.open){b.disabled=false;statusText('Could not connect to that party.')}},12000)}catch(e){b.disabled=false;statusText('Could not connect: '+e.message)}}
function message(c,m){if(!m)return;if(isHost){if(m.t==='hello'){if(players[m.id])return;if(Object.keys(players).length>=MAX){send(c,{t:'full'});c.close();return}c.pid=m.id;const s=spawnFor(m.id);players[m.id]={id:m.id,x:s[0],y:s[1],a:s[2],alive:true,k:0};send(c,{t:'state',map,players,id:m.id,mapName});broadcast({t:'snap',p:players})}else if(m.t==='input'&&players[m.id]){const p=players[m.id];p.x=m.x;p.y=m.y;p.a=m.a;if(m.attack&&performance.now()-lastStab>350){lastStab=performance.now();stab(m.id)}}return}if(m.t==='state'){map=m.map;players=m.players;myId=m.id;mapName=m.mapName||'Arena';$('mapName').textContent=mapName;if(players[myId])Object.assign(me,{x:players[myId].x,y:players[myId].y,a:players[myId].a,alive:players[myId].alive});start()}else if(m.t==='snap'){players=m.p||{};if(players[myId])Object.assign(me,{x:players[myId].x,y:players[myId].y,a:players[myId].a,alive:players[myId].alive})}else if(m.t==='hit'){flash=m.victim===myId?'STABBED!':'HIT!';if(m.respawn&&players[m.respawn.id])Object.assign(players[m.respawn.id],m.respawn,{alive:true});if(m.victim===myId&&m.respawn)Object.assign(me,{x:m.respawn.x,y:m.respawn.y,a:m.respawn.a,alive:true});setTimeout(()=>flash='',700)}else if(m.t==='full')statusText('That party is full.')}
function lineClear(x1,y1,x2,y2,maxDist){const dx=x2-x1,dy=y2-y1,d=Math.hypot(dx,dy);if(d>maxDist)return false;const steps=Math.ceil(d/.025);for(let i=1;i<=steps;i++){const t=i/steps;if(blocked(x1+dx*t,y1+dy*t))return false}return true}
function stab(id){const a=players[id];if(!a||!a.alive)return;const fx=Math.cos(a.a),fy=Math.sin(a.a);let best=null,bestD=KNIFE_RANGE;for(const k in players){const b=players[k];if(k===id||!b.alive)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>KNIFE_RANGE)continue;const forward=dx*fx+dy*fy;if(forward<=0)continue;const side=Math.abs(-dx*fy+dy*fx);if(side>.32)continue;if(!lineClear(a.x,a.y,b.x,b.y,KNIFE_RANGE))continue;if(d<bestD){bestD=d;best={k,b}}}if(!best)return;const s=spawnFor(best.k),b=best.b;b.x=s[0];b.y=s[1];b.a=s[2];b.alive=true;a.k++;broadcast({t:'hit',victim:best.k,respawn:{id:best.k,x:b.x,y:b.y,a:b.a}})}
function start(){if(running)return;if(!isHost&&(!conn||!conn.open))return;running=true;menu.hidden=true;canvas.hidden=false;$('hud').hidden=false;setControlMode(controlMode);resize();requestAnimationFrame(loop)}
function setControlMode(mode){controlMode=mode==='touch'?'touch':'keyboard';window.gameControlMode=controlMode;document.body.setAttribute('data-controls',controlMode);const tc=$('touchControls');if(tc){tc.hidden=controlMode!=='touch';tc.style.display=controlMode==='touch'?'block':'none'}const hint=$('controlHint');if(hint)hint.textContent=controlMode==='touch'?'TOUCH: joystick + drag to look + STAB':'WASD · mouse · SPACE';if(controlMode==='touch'&&document.pointerLockElement)document.exitPointerLock()}
function chooseControls(mode){setControlMode(mode);const prompt=$('controlPrompt');if(prompt)prompt.hidden=true;if(menu)menu.hidden=false}
window.chooseBackstabControls=chooseControls;
function resize(){canvas.width=Math.min(innerWidth,1280);canvas.height=Math.min(innerHeight,720)}
function move(dx,dy){if(!blocked(me.x+dx,me.y)&&!blocked(me.x+dx,me.y+.15)&&!blocked(me.x+dx,me.y-.15))me.x+=dx;if(!blocked(me.x,me.y+dy)&&!blocked(me.x+.15,me.y+dy)&&!blocked(me.x-.15,me.y+dy))me.y+=dy}
function ray(a){let x=me.x,y=me.y,d=0,sx=Math.cos(a),sy=Math.sin(a);while(d<30){x+=sx*.025;y+=sy*.025;d+=.025;if(blocked(x,y))break}return d}
function projectPoint(x,y,z,w,h){const dx=x-me.x,dy=y-me.y,ca=Math.cos(me.a),sa=Math.sin(me.a),forward=dx*ca+dy*sa,side=-dx*sa+dy*ca;if(forward<=.05)return null;const scale=(w/2)/Math.tan(FOV/2)/forward;return{x:w/2+side*scale,y:h/2+(CAM_H-z)*scale,forward,scale}}
function drawCube(p,w,h){const half=.28,depth=.28,height=.75,ca=Math.cos(p.a),sa=Math.sin(p.a),rx=-sa,ry=ca,v=[];for(const z of [0,height])for(const sx of [-half,half])for(const sy of [-depth,depth]){const wx=p.x+ca*sx+rx*sy,wy=p.y+sa*sx+ry*sy;v.push({wx,wy,z,p:projectPoint(wx,wy,z,w,h)})}if(v.some(q=>!q.p))return;const faces=[{ids:[0,1,3,2],color:'#238bd1'},{ids:[0,4,5,1],color:'#32bd50'},{ids:[1,5,7,3],color:'#238e3d'},{ids:[4,6,7,5],color:'#48c95b'},{ids:[2,3,7,6],color:'#1f7c38'},{ids:[0,2,6,4],color:'#2aa84a'}],visible=[];for(const f of faces){const a=v[f.ids[0]],b=v[f.ids[1]],c=v[f.ids[2]],ux=b.wx-a.wx,uy=b.wy-a.wy,uz=b.z-a.z,vx=c.wx-a.wx,vy=c.wy-a.wy,vz=c.z-a.z,nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;if(nx*(me.x-a.wx)+ny*(me.y-a.wy)+nz*(CAM_H-a.z)<=0)continue;const depth=f.ids.reduce((s,i)=>s+v[i].p.forward,0)/4;visible.push({f,depth})}visible.sort((a,b)=>b.depth-a.depth);ctx.strokeStyle='#071108';for(const q of visible){const pts=q.f.ids.map(i=>v[i].p);ctx.fillStyle=q.f.color;ctx.beginPath();pts.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.closePath();ctx.fill();ctx.stroke()}}
function render(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#171923';ctx.fillRect(0,0,w,h/2);ctx.fillStyle='#29251f';ctx.fillRect(0,h/2,w,h/2);const n=Math.ceil(w/3);for(let i=0;i<n;i++){const a=me.a-FOV/2+FOV*(i+.5)/n,d=ray(a)*Math.cos(a-me.a),hh=Math.min(h*2,h/Math.max(.01,d)),s=Math.max(25,150-d*4.2);ctx.fillStyle=`rgb(${s},${s},${Math.min(255,s+8)})`;ctx.fillRect(i*w/n,h/2-hh/2,w/n+1,hh)}const visible=[];for(const k in players){const p=players[k];if(k===myId||!p.alive)continue;const dx=p.x-me.x,dy=p.y-me.y,d=Math.hypot(dx,dy),angle=Math.atan2(dy,dx),a=Math.atan2(Math.sin(angle-me.a),Math.cos(angle-me.a));if(Math.abs(a)<FOV*.8&&lineClear(me.x,me.y,p.x,p.y,d+.01))visible.push({p,d})}visible.sort((a,b)=>b.d-a.d);visible.forEach(q=>drawCube(q.p,w,h));ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(w/2-8,h/2);ctx.lineTo(w/2+8,h/2);ctx.moveTo(w/2,h/2-8);ctx.lineTo(w/2,h/2+8);ctx.stroke();if(flash){ctx.fillStyle='#fff';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText(flash,w/2,h*.25)}}
function loop(t){const dt=Math.min(.04,(t-last||16)/1000);last=t;if(me.alive){const v=2.7*dt;let fx=0,fy=0;if(controlMode==='touch'){fx=touchX;fy=touchY}else{if(keys.KeyA)fx-=1;if(keys.KeyD)fx+=1;if(keys.KeyW)fy-=1;if(keys.KeyS)fy+=1}if(fx||fy){const len=Math.hypot(fx,fy)||1;fx/=len;fy/=len;move((Math.cos(me.a)*-fy+Math.cos(me.a+Math.PI/2)*fx)*v,(Math.sin(me.a)*-fy+Math.sin(me.a+Math.PI/2)*fx)*v)}}if(isHost){const p=players.host;if(p){p.x=me.x;p.y=me.y;p.a=me.a}if((keys.Space||touchStab)&&t-lastStab>350){lastStab=t;stab('host')}}if(t-lastNet>50){lastNet=t;if(isHost)broadcast({t:'snap',p:players});else send(conn,{t:'input',id:myId,x:me.x,y:me.y,a:me.a,attack:!!touchStab||!!keys.Space})}touchStab=false;render();$('players').textContent='Players: '+Object.keys(players).length;$('state').textContent=me.alive?'Alive — flank them':'ELIMINATED';requestAnimationFrame(loop)}
function setupTouch(){const stick=$('stick'),knob=$('knob'),look=$('lookArea'),stabButton=$('stabTouch');if(!stick||!knob||!look||!stabButton)return;const reset=()=>{stickActive=false;touchX=touchY=0;knob.style.transform='translate(0,0)'};const stickMove=e=>{const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=Math.max(20,Math.min(r.width,r.height)*.42),len=Math.hypot(dx,dy),scale=Math.min(1,max/(len||1)),x=dx*scale,y=dy*scale;knob.style.transform=`translate(${x}px,${y}px)`;touchX=x/max;touchY=y/max};stick.addEventListener('pointerdown',e=>{if(controlMode!=='touch')return;e.preventDefault();stickActive=true;stick.setPointerCapture(e.pointerId);stickMove(e)});stick.addEventListener('pointermove',e=>{if(controlMode==='touch'&&stickActive){e.preventDefault();stickMove(e)}});stick.addEventListener('pointerup',reset);stick.addEventListener('pointercancel',reset);look.addEventListener('pointerdown',e=>{if(controlMode!=='touch')return;e.preventDefault();lookActive=true;lastLookX=e.clientX;look.setPointerCapture(e.pointerId)});look.addEventListener('pointermove',e=>{if(controlMode==='touch'&&lookActive){e.preventDefault();me.a+=(e.clientX-lastLookX)*.008;lastLookX=e.clientX}});look.addEventListener('pointerup',()=>lookActive=false);look.addEventListener('pointercancel',()=>lookActive=false);stabButton.addEventListener('pointerdown',e=>{if(controlMode!=='touch')return;e.preventDefault();touchStab=true})}
$('hostTab').addEventListener('click',()=>{$('hostPanel').hidden=false;$('joinPanel').hidden=true;statusText('Ready to host a game.')});$('joinTab').addEventListener('click',()=>{$('hostPanel').hidden=true;$('joinPanel').hidden=false;statusText('Enter the host party code.')});$('hostBtn').addEventListener('click',hostGame);$('joinBtn').addEventListener('click',joinGame);
window.addEventListener('keydown',e=>{if(controlMode!=='keyboard')return;keys[e.code]=true;if(e.code==='Space')e.preventDefault();if(e.code==='KeyF'&&!canvas.hidden)document.documentElement.requestFullscreen?.()});window.addEventListener('keyup',e=>{if(controlMode==='keyboard')keys[e.code]=false});canvas.addEventListener('click',()=>{if(controlMode==='keyboard'&&!canvas.hidden)canvas.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(controlMode==='keyboard'&&document.pointerLockElement===canvas)me.a+=e.movementX*.0025});window.addEventListener('resize',resize);setupTouch();setControlMode(controlMode);