const W=16,H=12,CELL=40;let map=[];for(let y=0;y<H;y++)map[y]=Array(W).fill(0);for(let x=0;x<W;x++){map[0][x]=map[H-1][x]=1}for(let y=0;y<H;y++){map[y][0]=map[y][W-1]=1}
const ed=document.getElementById('mapEditor'),ec=ed.getContext('2d'),status=document.getElementById('status');let drawing=false;
function drawEditor(){ec.fillStyle='#171a21';ec.fillRect(0,0,ed.width,ed.height);for(let y=0;y<H;y++)for(let x=0;x<W;x++){ec.fillStyle=map[y][x]?'#667083':'#20252f';ec.fillRect(x*CELL+1,y*CELL+1,CELL-2,CELL-2);if(!map[y][x]){ec.fillStyle='#303744';ec.fillRect(x*CELL+19,y*CELL+19,2,2)}}}
function paint(e,v){let r=ed.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*ed.width/r.width/CELL),y=Math.floor((e.clientY-r.top)*ed.height/r.height/CELL);if(x>0&&x<W-1&&y>0&&y<H-1){map[y][x]=v;drawEditor()}}
ed.onmousedown=e=>{drawing=true;paint(e,e.button===0?1:0)};ed.onmousemove=e=>{if(drawing)paint(e,e.buttons&1?1:0)};ed.onmouseup=()=>drawing=false;ed.oncontextmenu=e=>e.preventDefault();drawEditor();
const hostPanel=document.getElementById('hostPanel'),joinPanel=document.getElementById('joinPanel'),finishPanel=document.getElementById('finishPanel');document.getElementById('hostTab').onclick=()=>{hostPanel.hidden=false;joinPanel.hidden=true};document.getElementById('joinTab').onclick=()=>{hostPanel.hidden=true;joinPanel.hidden=false};
let pc,dc,isHost=false,myId=null,players={},clientId=Math.random().toString(36).slice(2);const offerOut=document.getElementById('offerOut'),answerOut=document.getElementById('answerOut');
const waitIce=async c=>{if(c.iceGatheringState==='complete')return;await new Promise(r=>{let f=()=>{if(c.iceGatheringState==='complete'){c.removeEventListener('icegatheringstatechange',f);r()}};c.addEventListener('icegatheringstatechange',f);setTimeout(r,4000)})};
function setupDC(d){dc=d;dc.onopen=()=>{status.textContent='Connected! Click the game to capture the mouse.';if(!isHost)send({type:'hello',id:clientId})};dc.onmessage=e=>receive(JSON.parse(e.data));dc.onclose=()=>status.textContent='Connection closed.'}
async function makeHost(){isHost=true;myId='host';players[myId]={id:myId,x:2.5,y:2.5,a:0,alive:true,name:'HOST'};pc=new RTCPeerConnection();dc=pc.createDataChannel('game');setupDC(dc);pc.onicecandidate=()=>{};let o=await pc.createOffer();await pc.setLocalDescription(o);await waitIce(pc);offerOut.value=JSON.stringify(pc.localDescription);finishPanel.hidden=false;status.textContent='Offer ready. Send it to the player. After they answer, paste the answer below.';document.getElementById('hostBtn').disabled=true}
document.getElementById('hostBtn').onclick=makeHost;
document.getElementById('connectBtn').onclick=async()=>{try{await pc.setRemoteDescription(JSON.parse(document.getElementById('remoteAnswer').value));status.textContent='Connecting...'}catch(e){status.textContent='Invalid answer: '+e.message}};
async function makeJoin(){isHost=false;pc=new RTCPeerConnection();pc.ondatachannel=e=>setupDC(e.channel);try{await pc.setRemoteDescription(JSON.parse(document.getElementById('offerIn').value));let a=await pc.createAnswer();await pc.setLocalDescription(a);await waitIce(pc);answerOut.value=JSON.stringify(pc.localDescription);status.textContent='Answer ready. Send it to the host.';document.getElementById('joinBtn').disabled=true;startWhenReady()}catch(e){status.textContent='Invalid offer: '+e.message}}
document.getElementById('joinBtn').onclick=makeJoin;
function send(o){if(dc?.readyState==='open')dc.send(JSON.stringify(o))}function broadcast(o){for(let d of peers.values())if(d.readyState==='open')d.send(JSON.stringify(o))}let peers=new Map();
function receive(m){if(isHost){if(m.type==='hello'){let id=m.id;players[id]={id,x:3.5+Object.keys(players).length%5,y:3.5+Math.floor(Object.keys(players).length/5),a:0,alive:true,name:'P'+Object.keys(players).length};let c=hostPeerFor(id);c&&c.send(JSON.stringify({type:'state',map,players,myId:id}));}else if(m.type==='input'){let p=players[m.id];if(p&&p.alive){p.x=m.x;p.y=m.y;p.a=m.a;p.attack=m.attack||0;resolveAttack(m.id)}}else if(m.type==='ping')broadcast(m)}else{if(m.type==='state'){map=m.map;players=m.players;myId=m.myId;startWhenReady()}if(m.type==='snapshot'){players=m.players}if(m.type==='hit'){flashHit=m.target===myId?'YOU WERE STABBED':'STAB!'}}}
// A host uses one WebRTC channel per peer. The first connection is the host's own data channel; additional peers use a simple relay protocol.
function hostPeerFor(id){return id==='host'?dc:peers.get(id)}
// Host-mediated relay: clients send input over their host channel; host broadcasts snapshots on the same channel.
function resolveAttack(id){let a=players[id];if(!a.attack)return;for(let k in players){let b=players[k];if(k===id||!b.alive)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>.95)continue;let ang=Math.atan2(dy,dx),diff=Math.abs(Math.atan2(Math.sin(ang-a.a),Math.cos(ang-a.a)));if(diff<.65)continue; // attacker must be roughly behind/side of victim
let fromVictim=Math.atan2(a.y-b.y,a.x-b.x),behind=Math.cos(fromVictim-b.a)<=0;if(behind){b.alive=false;a.kills=(a.kills||0)+1;broadcast({type:'hit',target:k});}}
}
let keys={},flashHit='',lastSend=0;addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.addEventListener('click',()=>{if(game.hidden)return;game.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===game)me.a+=e.movementX*.0025});
let me={x:2.5,y:2.5,a:0,alive:true},game=document.getElementById('game'),g=game.getContext('2d'),running=false;
function startWhenReady(){if(running||!dc||dc.readyState!=='open')return;running=true;document.getElementById('menu').hidden=true;game.hidden=false;document.getElementById('hud').hidden=false;resize();requestAnimationFrame(loop)}
function resize(){game.width=Math.min(innerWidth,1280);game.height=Math.min(innerHeight,720)}addEventListener('resize',resize);
function wall(x,y){return x<0||y<0||x>=W||y>=H||map[Math.floor(y)]?.[Math.floor(x)]===1}function move(p,dx,dy){if(!wall(p.x+dx,p.y))p.x+=dx;if(!wall(p.x,p.y+dy))p.y+=dy}
function cast(a){let sin=Math.sin(a),cos=Math.cos(a),mx=Math.floor(me.x),my=Math.floor(me.y),ddx=Math.abs(1/(cos||1e-9)),ddy=Math.abs(1/(sin||1e-9));let sx=cos<0?-1:1,sy=sin<0?-1:1,sdx=cos<0?(me.x-mx)*ddx:(mx+1-me.x)*ddx,sdy=sin<0?(me.y-my)*ddy:(my+1-me.y)*ddy;let side=0,d=0;for(let i=0;i<64;i++){if(sdx<sdy){sdx+=ddx;mx+=sx;side=0}else{sdy+=ddy;my+=sy;side=1}if(map[my]?.[mx]){d=side===0?(mx-me.x+(1-sx)/2)/(cos||1e-9):(my-me.y+(1-sy)/2)/(sin||1e-9);break}}return {d:Math.abs(d)||64,side}}
function render(){let w=game.width,h=game.height;g.fillStyle='#171923';g.fillRect(0,0,w,h/2);g.fillStyle='#29251f';g.fillRect(0,h/2,w,h/2);let fov=Math.PI/3,cols=Math.ceil(w/3),cw=w/cols;for(let i=0;i<cols;i++){let ra=me.a-fov/2+fov*(i+.5)/cols,r=cast(ra),d=r.d*Math.cos(ra-me.a),hh=Math.min(h*2,h/d),x=i*cw;g.fillStyle=r.side?'#737b88':'#8993a2';g.fillRect(x,h/2-hh/2,cw+1,hh)}let visible=[];for(let id in players){let p=players[id];if(!p.alive||id===myId&&!isHost)continue;let dx=p.x-me.x,dy=p.y-me.y,dist=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)-me.a;ang=Math.atan2(Math.sin(ang),Math.cos(ang));if(Math.abs(ang)<fov*.65&&dist>.2){let sx=w/2+Math.tan(ang)/(Math.tan(fov/2))*w/2,sz=Math.min(h*1.5,h/(dist*.9));if(cast(me.a+ang).d>dist-.15)visible.push({sx,sz,dist,p})}}visible.sort((a,b)=>b.dist-a.dist);for(let o of visible){g.fillStyle='#d7dbe3';g.fillRect(o.sx-o.sz*.12,h/2-o.sz*.75,o.sz*.24,o.sz*.7);g.fillStyle='#b9c1cf';g.beginPath();g.arc(o.sx,h/2-o.sz*.88,o.sz*.16,0,7);g.fill();g.fillStyle='#111';g.fillRect(o.sx-o.sz*.08,h/2-o.sz*.92,o.sz*.05,o.sz*.035);g.fillRect(o.sx+o.sz*.03,h/2-o.sz*.92,o.sz*.05,o.sz*.035)}g.strokeStyle='#fff';g.lineWidth=2;g.beginPath();g.moveTo(w/2-8,h/2);g.lineTo(w/2+8,h/2);g.moveTo(w/2,h/2-8);g.lineTo(w/2,h/2+8);g.stroke();if(flashHit){g.fillStyle='#fff';g.font='bold 32px system-ui';g.textAlign='center';g.fillText(flashHit,w/2,h*.25);setTimeout(()=>flashHit='',450)}}
function loop(t){let dt=Math.min(.04,(t-(loop.last||t))/1000);loop.last=t;if(me.alive){let s=2.7*dt;if(keys.w)move(me,Math.cos(me.a)*s,Math.sin(me.a)*s);if(keys.s)move(me,-Math.cos(me.a)*s,-Math.sin(me.a)*s);if(keys.a)move(me,Math.cos(me.a-Math.PI/2)*s,Math.sin(me.a-Math.PI/2)*s);if(keys.d)move(me,Math.cos(me.a+Math.PI/2)*s,Math.sin(me.a+Math.PI/2)*s)}render();document.getElementById('players').textContent='Players: '+Object.keys(players).length;document.getElementById('state').textContent=me.alive?'Alive — find their back':'ELIMINATED';if(dc?.readyState==='open'&&t-lastSend>50){lastSend=t;send({type:'input',id:myId,x:me.x,y:me.y,a:me.a,attack:keys[' ' ]?1:0})}requestAnimationFrame(loop)}
// Space performs the stab. A successful hit requires the attacker to be behind or directly beside the victim.
addEventListener('keydown',e=>{if(e.code==='Space')e.preventDefault()});
